version: '2'
services:
  netdata:
    image: titpetric/netdata:latest
    labels:
      io.rancher.scheduler.global: 'true'
    cap_add:
    - SYS_PTRACE
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - ${DIR}/netdata.conf:/etc/netdata/netdata.conf
    environment:
      NETDATA_PORT: "${NETDATA_PORT}"
