version: '2'

services:

  nginx:
    image: emcniece/nginx-cache-purge-wp:1.13-alpine
    ports:
      - ${PORT}:80
    links:
      - wordpress:wp-fpm
    volumes:
      - wp-local:/var/www/html
    labels:
      rgon.ssl: ${SSL}
      rgon.domain: ${HOST}
      rgon.redirect: ${REDIRECT}

  wordpress:
    tty: true
    stdin_open: true
    image: emcniece/wordpress:4-php7.1-fpm-alpine
    volumes:
      - wp-local:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_NAME}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASS}
      WPFPM_WP_REDIS_HOST: redis
      WPFPM_RT_WP_NGINX_HELPER_CACHE_PATH: "/tmp/cache"

  mysql:
    image: mariadb
    command: mysqld --innodb-buffer-pool-size=${INNODB_BUF}M
    volumes:
      - mysql-local:/var/lib/mysql:rw
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASS}

  redis:
    image: redis:3-alpine

  bg-sync:
    image: cweagans/bg-sync
    volumes:
      - wp-local:/source/wp
      - wp-nfs:/destination/wp

      # DB sync is possible, but really heavy. Consider dumping
      # db to file and syncing with WP files instead.
      # IF enabling this, remove the SYNC_SOURCE variable.
      #- mysql-local:/source/mysql
      #- mysql-nfs:/destination/mysql
    environment:
      - SYNC_SOURCE=/source/wp/wp-content
      - SYNC_VERBOSE=1

volumes:
  wp-local:
    driver: local
  wp-nfs:
    driver: ${STORAGE_DRIVER}
  mysql-local:
    driver: local
# Enable if syncing DB
#  mysql-nfs:
#    driver: ${STORAGE_DRIVER}
