.catalog:
  name: WordPress PHP7 MySQL
  version: 0.0.4
  description: |
    One-click WordPress w/ PHP7-FPM, Redis, Nginx, MySQL
  maintainer: "Eric McNiece <emcniece@gmail.com>"
  uuid: wp-php7-mysql-0
  questions:
    - variable: "PORT"
      description: |
        Port for HTTP traffic. Leave blank to let Rancher choose a random port.
      label: "Port"
      required: false
      type: "int"

    - variable: "MYSQL_NAME"
      description: "Database Name"
      label: "DB Name"
      required: true
      type: "string"
      default: "wordpress"
    - variable: "MYSQL_USER"
      description: "Database User"
      label: "DB User"
      required: true
      type: "string"
      default: "wordpress"
    - variable: "MYSQL_PASS"
      description: "Database Password"
      label: "DB Password"
      required: true
      type: "password"
      default: "wordpress"
    - variable: "INNODB_BUF"
      description: "Should be total size of DB + 60%"
      label: "InnoDB Buffer Pool Size (MB)"
      required: true
      type: "integer"
      default: "20"

    - variable: "HOST"
      description: "RGON-Proxy Hostname for WordPress (FQDN)"
      label: "Hostname"
      required: false
      type: "string"
    - variable: "SSL"
      description: "Enable RGON-Proxy SSL certificate"
      label: "SSL Certificate"
      required: true
      type: "boolean"
      default: false
    - variable: "REDIRECT"
      label: "HTTPS Redirect"
      description: "Enable http/https redirects for RGON-Proxy"
      required: false
      default: "http"
      type: "enum"
      options:
        - http
        - https

    - variable: STORAGE_LOCAL
      label: Local Storage Driver
      description: "Set directory if needed, or set to 'local' for a named volume"
      type: "string"
      default: "/home/rancher/mysite/wp"
    - variable: STORAGE_BACKUP
      label: Backup Storage Driver
      description: "Set directory if needed, or set to 'local' for a named volume"
      type: "string"
      default: "/home/rancher/mysite/backup"
    - variable: STORAGE_REMOTE
      label: Remote Storage Driver
      description: "Set dir or driver. Eg. 'rancher-nfs'"
      type: "string"
      default: "rancher-nfs"

nginx:
  scale: 1
wordpress:
  scale: 1
mysql:
  scale: 1
mysql-helper:
  scale: 1
redis:
  scale: 1
bg-sync:
  scale: 1
