name: WordPress PHP7
description: |
  One-click WordPress w/ PHP7-FPM, Redis, Nginx
version: 0.0.1-mysql
category: Blogging
maintainer: "Eric McNiece <emcniece@gmail.com>"
projectURL: https://hub.docker.com/r/emcniece/wp-php7-nginx/