name: strider-cd
description: |
  Strider Continuous Deployment agent
version: 0.0.4-rancher1
category: Continuous Integration
maintainer: "Eric McNiece <emcniece@gmail.com>, Andrew Cutler <candrew@panubo.io>"
projectURL: https://github.com/macropin/docker-strider