name: NFSHost
description: |
  Creates an NFS which is linked to a directory on the docker host machine.
version: 0.0.3
category: Storage
maintainer: "Eric McNiece, Steven Bjornson"
projectURL: https://github.com/emcniece/rancher-catalog