name: NetData
description: |
  Real-time performance monitoring, done righter - with exposed config!
version: 0.0.2
category: System Management
maintainer: "Eric McNiece <emcniece@gmail.com>"
projectURL: https://github.com/emcniece/rancher-catalog