name: NetData Plus
description: |
  Real-time performance monitoring, with exposed config!
version: 0.0.3
category: System Management
maintainer: "Eric McNiece <emcniece@gmail.com>"
projectURL: https://github.com/emcniece/rancher-catalog