.catalog:
  name: WordPress PHP7
  version: 0.0.1
  description: |
    Strider Continuous Deployment agent
  maintainer: "Eric McNiece <emcniece@gmail.com>"
  uuid: wp-php7-0
  questions:
    - variable: "DIR"
      label: "Storage directory"
      description: "Path of shared storage to use for WordPress and the import files. No trailing slash!"
      required: true
      type: "string"
    - variable: "PORT"
      description: |
        Port for HTTP traffic. Leave blank to let Rancher choose a random port.
      label: "Port"
      required: false
      type: "int"
    - variable: "HOST"
      description: "Hostname for WordPress (FQDN)"
      label: "Hostname"
      required: false
      type: "string"
    - variable: "LETSENCRYPT_EMAIL"
      description: "Adds the `LETSENCRYPT_EMAIL` environment variable"
      label: "Let's Encrypt Email Address"
      required: false
      type: "string"