.catalog:
  name: WordPress PHP7
  version: 0.0.1
  description: |
    One-click WordPress w/ PHP7-FPM, Redis, Nginx
  maintainer: "Eric McNiece <emcniece@gmail.com>"
  uuid: wp-php7-0
  questions:
    - variable: "DIR"
      label: "Storage directory"
      description: "Path of shared storage to use for WordPress and the import files. No trailing slash!"
      required: true
      type: "string"
    - variable: "PORT"
      description: |
        Port for HTTP traffic. Leave blank to let Rancher choose a random port.
      label: "Port"
      required: false
      type: "int"
    - variable: "HOST"
      description: "RGON-Proxy Hostname for WordPress (FQDN)"
      label: "Hostname"
      required: false
      type: "string"
    - variable: "SSL"
      description: "Enable RGON-Proxy SSL certificate"
      label: "SSL Certificate"
      required: true
      type: "boolean"
      default: false
    - variable: "REDIRECT"
      label: "HTTPS Redirect"
      description: "Enable http/https redirects for RGON-Proxy"
      required: false
      default: "http"
      type: "enum"
      options:
        - http
        - https