name: Nginx-Friendly Registry
description: |
  Docker Registry compatible with an Nginx proxy
version: 0.0.2-rancher1
category: clustering
maintainer: "Eric McNiece <emcniece@gmail.com>, Raul Sanchez"
projectURL: https://github.com/emcniece/rancher-catalog